ADMIN_NONE = "" 
ADMIN_KICK = "c"
ADMIN_BAN = "d"
ADMIN_MAP = "g"
ADMIN_RCON = "m"
ADMIN_CHAT = "j"

AllFlags = { ADMIN_NONE, ADMIN_KICK, ADMIN_BAN, ADMIN_MAP, ADMIN_RCON, ADMIN_CHAT }

TEAM_RANDOM = -1
TEAM_READYROOM = 0
TEAM_ONE = 1
TEAM_TWO = 2
TEAM_SPECTATE = 3

validTeams = { TEAM_READYROOM, TEAM_ONE, TEAM_TWO }

STEAM_ID_UNKNOWN = "STEAM_ID_UNKNOWN"

PRINT_CHAT = "chat"
PRINT_CONSOLE = "console"
PRINT_CENTER = "center"
PRINT_COORDINATE = "coordinate"
PRINT_ALL_PLAYERS = 0